In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('original_dataset.csv',encoding='latin-1')

In [3]:
df.head()

,DisNo.,Historic,Classification Key,Disaster Group,Disaster Subgroup,Disaster Type,Disaster Subtype,External IDs,Event Name,ISO,...,Reconstruction Costs ('000 US$),"Reconstruction Costs, Adjusted ('000 US$)",Insured Damage ('000 US$),"Insured Damage, Adjusted ('000 US$)",Total Damage ('000 US$),"Total Damage, Adjusted ('000 US$)",CPI,Admin Units,Entry Date,Last Update
0,1999-9388-DJI,No,nat-cli-dro-dro,Natural,Climatological,Drought,Drought,NaN,NaN,DJI,...,NaN,NaN,NaN,NaN,NaN,NaN,58.111474,"[{""adm1_code"":1093,""adm1_name"":""Ali Sabieh""},{...",2006-03-01,2023-09-25
1,1999-9388-SDN,No,nat-cli-dro-dro,Natural,Climatological,Drought,Drought,NaN,NaN,SDN,...,NaN,NaN,NaN,NaN,NaN,NaN,56.514291,"[{""adm1_code"":2757,""adm1_name"":""Northern Darfu...",2006-03-08,2023-09-25
2,1999-9388-SOM,No,nat-cli-dro-dro,Natural,Climatological,Drought,Drought,NaN,NaN,SOM,...,NaN,NaN,NaN,NaN,NaN,NaN,56.514291,"[{""adm1_code"":2691,""adm1_name"":""Bay""},{""adm1_c...",2006-03-08,2023-09-25
3,2000-0002-AGO,No,nat-hyd-flo-riv,Natural,Hydrological,Flood,Riverine flood,NaN,NaN,AGO,...,NaN,NaN,NaN,NaN,10000.0,17695.0,56.514291,"[{""adm2_code"":4214,""adm2_name"":""Baia Farta""},{...",2005-02-03,2023-09-25
4,2000-0003-BGD,No,nat-met-ext-col,Natural,Meteorological,Extreme temperature,Cold wave,NaN,NaN,BGD,...,NaN,NaN,NaN,NaN,NaN,NaN,56.514291,"[{""adm1_code"":575,""adm1_name"":""Barisal""},{""adm...",2003-07-01,2023-09-25

In [4]:
df = df.drop(columns=['DisNo.','Historic','Classification Key','Disaster Group','External IDs','Event Name','ISO','Origin','Associated Types','Latitude','Longitude','Admin Units','Entry Date','Last Update'],axis=1)

In [5]:
df.head()

,Disaster Subgroup,Disaster Type,Disaster Subtype,Country,Subregion,Region,Location,OFDA/BHA Response,Appeal,Declaration,...,No. Affected,No. Homeless,Total Affected,Reconstruction Costs ('000 US$),"Reconstruction Costs, Adjusted ('000 US$)",Insured Damage ('000 US$),"Insured Damage, Adjusted ('000 US$)",Total Damage ('000 US$),"Total Damage, Adjusted ('000 US$)",CPI
0,Climatological,Drought,Drought,Djibouti,Sub-Saharan Africa,Africa,"Ali Sabieh, Dikhil, Djibouti, Obock, Tadjourah...",Yes,No,No,...,100000.0,NaN,100000.0,NaN,NaN,NaN,NaN,NaN,NaN,58.111474
1,Climatological,Drought,Drought,Sudan,Northern Africa,Africa,"Northern Darfur, Northern Kordofan, Red Sea pr...",No,No,No,...,2000000.0,NaN,2000000.0,NaN,NaN,NaN,NaN,NaN,NaN,56.514291
2,Climatological,Drought,Drought,Somalia,Sub-Saharan Africa,Africa,"Ceel Barde, Rab Dhuure, Tayeeglow, Xudur distr...",No,No,No,...,1200000.0,NaN,1200000.0,NaN,NaN,NaN,NaN,NaN,NaN,56.514291
3,Hydrological,Flood,Riverine flood,Angola,Sub-Saharan Africa,Africa,"Dombre Grande village (Baia Farta district, Be...",No,No,Yes,...,70000.0,NaN,70000.0,NaN,NaN,NaN,NaN,10000.0,17695.0,56.514291
4,Meteorological,Extreme temperature,Cold wave,Bangladesh,Southern Asia,Asia,"Barisal, Chittagong, Dhaka, Khulna, Rajshahi, ...",No,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56.514291

In [6]:
df[["AID Contribution ('000 US$)","No. Affected", "No. Homeless", "Reconstruction Costs ('000 US$)", "Reconstruction Costs, Adjusted ('000 US$)","Insured Damage ('000 US$)","Insured Damage, Adjusted ('000 US$)","Total Damage ('000 US$)","Total Damage, Adjusted ('000 US$)"]] = df[["AID Contribution ('000 US$)","No. Affected", "No. Homeless", "Reconstruction Costs ('000 US$)", "Reconstruction Costs, Adjusted ('000 US$)","Insured Damage ('000 US$)","Insured Damage, Adjusted ('000 US$)","Total Damage ('000 US$)","Total Damage, Adjusted ('000 US$)"]].fillna(0)

In [7]:
df.isna().sum()

Disaster Subgroup                               0
Disaster Type                                   0
Disaster Subtype                                0
Country                                         0
Subregion                                       0
Region                                          0
Location                                      386
OFDA/BHA Response                               0
Appeal                                          0
Declaration                                     0
AID Contribution ('000 US$)                     0
Magnitude                                    6782
Magnitude Scale                              1070
River Basin                                  8956
Start Year                                      0
Start Month                                    68
Start Day                                    1497
End Year                                        0
End Month                                     162
End Day                                      1433
Total Deaths                                 2910
No. Injured                                  7319
No. Affected                                    0
No. Homeless                                    0
Total Affected                               1969
Reconstruction Costs ('000 US$)                 0
Reconstruction Costs, Adjusted ('000 US$)       0
Insured Damage ('000 US$)                       0
Insured Damage, Adjusted ('000 US$)             0
Total Damage ('000 US$)                         0
Total Damage, Adjusted ('000 US$)               0
CPI                                           225
dtype: int64

In [8]:
# Column to check
columns_to_check = ['Total Deaths','Start Day','End Day','Location']
for column_to_check in columns_to_check:
  # Remove rows where the value in the specified column is 0 or NA
  df = df[~df[column_to_check].isna() & (df[column_to_check] != 0)]

df.shape

(6245, 32)

In [9]:
df.isna().sum()

Disaster Subgroup                               0
Disaster Type                                   0
Disaster Subtype                                0
Country                                         0
Subregion                                       0
Region                                          0
Location                                        0
OFDA/BHA Response                               0
Appeal                                          0
Declaration                                     0
AID Contribution ('000 US$)                     0
Magnitude                                    3849
Magnitude Scale                               725
River Basin                                  5413
Start Year                                      0
Start Month                                     0
Start Day                                       0
End Year                                        0
End Month                                       0
End Day                                         0
Total Deaths                                    0
No. Injured                                  4001
No. Affected                                    0
No. Homeless                                    0
Total Affected                               1075
Reconstruction Costs ('000 US$)                 0
Reconstruction Costs, Adjusted ('000 US$)       0
Insured Damage ('000 US$)                       0
Insured Damage, Adjusted ('000 US$)             0
Total Damage ('000 US$)                         0
Total Damage, Adjusted ('000 US$)               0
CPI                                           147
dtype: int64

In [10]:
df['Start Year'] = df['Start Year'].astype(int)
df['Start Month'] = df['Start Month'].astype(int)
df['Start Day'] = df['Start Day'].astype(int)
df['End Year'] = df['End Year'].astype(int)
df['End Month'] = df['End Month'].astype(int)
df['End Day'] = df['End Day'].astype(int)
df['Start_Date'] = pd.to_datetime(df['Start Year'].astype(str) + '-' + df['Start Month'].astype(str) + '-' + df['Start Day'].astype(str))
df['End_Date'] = pd.to_datetime(df['End Year'].astype(str) + '-' + df['End Month'].astype(str) + '-' + df['End Day'].astype(str))
df['Duration'] = (df['End_Date'] - df['Start_Date']).dt.days
df

,Disaster Subgroup,Disaster Type,Disaster Subtype,Country,Subregion,Region,Location,OFDA/BHA Response,Appeal,Declaration,...,Reconstruction Costs ('000 US$),"Reconstruction Costs, Adjusted ('000 US$)",Insured Damage ('000 US$),"Insured Damage, Adjusted ('000 US$)",Total Damage ('000 US$),"Total Damage, Adjusted ('000 US$)",CPI,Start_Date,End_Date,Duration
3,Hydrological,Flood,Riverine flood,Angola,Sub-Saharan Africa,Africa,"Dombre Grande village (Baia Farta district, Be...",No,No,Yes,...,0.0,0.0,0.0,0.0,10000.0,17695.0,56.514291,2000-01-08,2000-01-15,7
6,Meteorological,Storm,Storm (General),Iran (Islamic Republic of),Southern Asia,Asia,Gilan province,No,No,No,...,0.0,0.0,0.0,0.0,0.0,0.0,56.514291,2000-01-18,2000-01-18,0
7,Hydrological,Flood,Riverine flood,Mozambique,Sub-Saharan Africa,Africa,"Matutuine, Manhica, Magude, Marracuene distric...",Yes,No,No,...,0.0,0.0,1500.0,2654.0,419200.0,741759.0,56.514291,2000-01-26,2000-03-27,61
9,Hydrological,Flood,Riverine flood,Brazil,Latin America and the Caribbean,Americas,"Rio de Janeiro city (Rio de Janeiro district, ...",No,No,Yes,...,0.0,0.0,0.0,0.0,0.0,0.0,56.514291,2000-01-01,2000-01-06,5
11,Meteorological,Storm,Tornado,United States of America,Northern America,Americas,"Crittenden, Daviess, Webster districts (Kentuc...",No,No,No,...,0.0,0.0,200500.0,354778.0,210000.0,371587.0,56.514291,2000-01-02,2000-01-04,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10139,Hydrological,Flood,Flash flood,Bangladesh,Southern Asia,Asia,"Lakshmipur, Cumilla, Feni, and Noakhali distri...",No,No,No,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,2024-08-20,2024-08-26,6
10140,Hydrological,Flood,Flash flood,India,Southern Asia,Asia,Tripura state,No,No,No,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,2024-08-19,2024-08-23,4
10141,Hydrological,Mass movement (wet),Landslide (wet),India,Southern Asia,Asia,"Dipu Dara village (Singtam municipality, Gangt...",No,No,No,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,2024-08-22,2024-08-22,0
10142,Hydrological,Flood,Flood (General),Thailand,South-eastern Asia,Asia,"Phetchabun, Chiang Rai, Chiang Mai, Nan, Phaya...",No,No,No,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,2024-08-16,2024-08-26,10
10143,Hydrological,Flood,Flood (General),Nigeria,Sub-Saharan Africa,Africa,Adamawa state,No,No,No,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,2024-08-20,2024-08-24,4

In [11]:
df = df.drop(columns=['Start Year','Start Month','Start Day','End Day','End Month','End Year'],axis=1)
df.head()

,Disaster Subgroup,Disaster Type,Disaster Subtype,Country,Subregion,Region,Location,OFDA/BHA Response,Appeal,Declaration,...,Reconstruction Costs ('000 US$),"Reconstruction Costs, Adjusted ('000 US$)",Insured Damage ('000 US$),"Insured Damage, Adjusted ('000 US$)",Total Damage ('000 US$),"Total Damage, Adjusted ('000 US$)",CPI,Start_Date,End_Date,Duration
3,Hydrological,Flood,Riverine flood,Angola,Sub-Saharan Africa,Africa,"Dombre Grande village (Baia Farta district, Be...",No,No,Yes,...,0.0,0.0,0.0,0.0,10000.0,17695.0,56.514291,2000-01-08,2000-01-15,7
6,Meteorological,Storm,Storm (General),Iran (Islamic Republic of),Southern Asia,Asia,Gilan province,No,No,No,...,0.0,0.0,0.0,0.0,0.0,0.0,56.514291,2000-01-18,2000-01-18,0
7,Hydrological,Flood,Riverine flood,Mozambique,Sub-Saharan Africa,Africa,"Matutuine, Manhica, Magude, Marracuene distric...",Yes,No,No,...,0.0,0.0,1500.0,2654.0,419200.0,741759.0,56.514291,2000-01-26,2000-03-27,61
9,Hydrological,Flood,Riverine flood,Brazil,Latin America and the Caribbean,Americas,"Rio de Janeiro city (Rio de Janeiro district, ...",No,No,Yes,...,0.0,0.0,0.0,0.0,0.0,0.0,56.514291,2000-01-01,2000-01-06,5
11,Meteorological,Storm,Tornado,United States of America,Northern America,Americas,"Crittenden, Daviess, Webster districts (Kentuc...",No,No,No,...,0.0,0.0,200500.0,354778.0,210000.0,371587.0,56.514291,2000-01-02,2000-01-04,2

In [12]:
df.isna().sum()

Disaster Subgroup                               0
Disaster Type                                   0
Disaster Subtype                                0
Country                                         0
Subregion                                       0
Region                                          0
Location                                        0
OFDA/BHA Response                               0
Appeal                                          0
Declaration                                     0
AID Contribution ('000 US$)                     0
Magnitude                                    3849
Magnitude Scale                               725
River Basin                                  5413
Total Deaths                                    0
No. Injured                                  4001
No. Affected                                    0
No. Homeless                                    0
Total Affected                               1075
Reconstruction Costs ('000 US$)                 0
Reconstruction Costs, Adjusted ('000 US$)       0
Insured Damage ('000 US$)                       0
Insured Damage, Adjusted ('000 US$)             0
Total Damage ('000 US$)                         0
Total Damage, Adjusted ('000 US$)               0
CPI                                           147
Start_Date                                      0
End_Date                                        0
Duration                                        0
dtype: int64

In [13]:
df['CPI'] = df['CPI'].fillna(0)
df.isna().sum()

Disaster Subgroup                               0
Disaster Type                                   0
Disaster Subtype                                0
Country                                         0
Subregion                                       0
Region                                          0
Location                                        0
OFDA/BHA Response                               0
Appeal                                          0
Declaration                                     0
AID Contribution ('000 US$)                     0
Magnitude                                    3849
Magnitude Scale                               725
River Basin                                  5413
Total Deaths                                    0
No. Injured                                  4001
No. Affected                                    0
No. Homeless                                    0
Total Affected                               1075
Reconstruction Costs ('000 US$)                 0
Reconstruction Costs, Adjusted ('000 US$)       0
Insured Damage ('000 US$)                       0
Insured Damage, Adjusted ('000 US$)             0
Total Damage ('000 US$)                         0
Total Damage, Adjusted ('000 US$)               0
CPI                                             0
Start_Date                                      0
End_Date                                        0
Duration                                        0
dtype: int64

In [14]:
df.shape

(6245, 29)

In [28]:
df.to_csv('cleaned_data.csv', index=False)